---
title: "combine_data"
author: "Weihao Li"
date: "2020年4月25日"
output: html_document
---

```{r}
library(tidyverse)
# combine hotspots
hotspots_3km = read_csv('data/hotspots_3km.csv')
hotspots_3km_mean = read_csv('data/hotspots_3km_mean.csv')
hotspots_3km_max = read_csv('data/hotspots_3km_max.csv')
hotspots_6km = read_csv('data/hotspots_6km.csv')
hotspots_6km_mean = read_csv('data/hotspots_6km_mean.csv')
hotspots_6km_max = read_csv('data/hotspots_6km_max.csv')
hotspots_9km = read_csv('data/hotspots_9km.csv')
```


```{r}
temp = hotspots_3km %>%
  arrange(obs_id) %>%
  select(obs_id, fire_id_3km)

temp = hotspots_3km_max %>%
  arrange(obs_id) %>%
  select(obs_id, fire_id_3km_max) %>%
  full_join(temp, by = c("obs_id"))

temp = hotspots_3km_mean %>%
  arrange(obs_id) %>%
  select(obs_id, fire_id_3km_mean) %>%
  full_join(temp, by = c("obs_id"))

temp = hotspots_6km %>%
  arrange(obs_id) %>%
  select(obs_id, fire_id_6km) %>%
  full_join(temp, by = c("obs_id"))

temp = hotspots_6km_max %>%
  arrange(obs_id) %>%
  select(obs_id, fire_id_6km_max) %>%
  full_join(temp, by = c("obs_id"))

temp = hotspots_6km_mean %>%
  arrange(obs_id) %>%
  select(obs_id, fire_id_6km_mean) %>%
  full_join(temp, by = c("obs_id"))

temp = hotspots_9km %>%
  arrange(obs_id) %>%
  select(obs_id, fire_id_9km) %>%
  full_join(temp, by = c("obs_id"))

temp = hotspots_3km %>%
  arrange(obs_id) %>%
  select(-fire_id_3km) %>%
  full_join(temp, by = c("obs_id"))

rm(hotspots_3km)
rm(hotspots_3km_max)
rm(hotspots_3km_mean)
rm(hotspots_6km)
rm(hotspots_6km_max)
rm(hotspots_6km_mean)
rm(hotspots_9km)
```

```{r }
library(bomrang)
```

```{r 'get_stations_ids'}
# get all stations and sorted by distance from MEL
station_ids = sweep_for_stations(latlon = c(-37.8136, 144.9631))
```

```{r 'filter_VIC_stations'}
# filter VIC stations
VIC_station_ids = station_ids %>%
  filter(state == 'VIC')
rm(station_ids)
```

```{r 'define_get_historical_weather'}

get_comprehensive_historical_weather <- function(station_id){
  
# requst weather data
rain_record = try(get_historical(station_id, type = "rain"))
min_record = try(get_historical(station_id, type = "min"))
max_record = try(get_historical(station_id, type = "max"))
solar_record = try(get_historical(station_id, type = "solar"))

# keep useful information
if (class(rain_record) != "try-error"){
  rain_record = select(rain_record, -quality, -product_code)
  }

if (class(min_record) != "try-error"){
  min_record = select(min_record, -quality, -product_code)
}

if (class(max_record) != "try-error"){
  max_record = select(max_record, -quality, -product_code)
}

if (class(solar_record) != "try-error"){
  solar_record = select(solar_record, -product_code)
}

temp = list()
temp[[1]] = rain_record
temp[[2]] = min_record
temp[[3]] = max_record
temp[[4]] = solar_record

result = NULL
  
for (i in 1:4){
  if (class(temp[[i]]) != "try-error") {
    if (is.null(result)){
      result = temp[[i]]
    } else {
      result = full_join(result, temp[[i]], by = c('year','month','day','station_number'))
    }
    
  } 
}

return(result)
}


```

```{r 'get_historical_weather_example', warning= FALSE}
weather_record = list()
for (i in seq(1,nrow(VIC_station_ids))){
  weather_ex = get_comprehensive_historical_weather(VIC_station_ids$site[i])
  weather_record[[i]] = weather_ex
}
```

```{r}
weather_combine = bind_rows(weather_record)
write.csv(weather_combine, 'data/weather.csv')
```

```{r}
library(sf)
temp_stations = st_as_sf(VIC_station_ids, coords = c("lon","lat"), crs = 4326)
temp_hotspots = st_as_sf(temp, coords = c("lon","lat"), crs = 4326)
```

```{r}
temp$nearest_station = VIC_station_ids$site[st_nearest_feature(temp_hotspots, temp_stations)]
temp$nearest_station_name = VIC_station_ids$name[st_nearest_feature(temp_hotspots, temp_stations)]
```

```{r}
# read all roads in australia
au_road = st_read("australia-latest-free.shp/gis_osm_roads_free_1.shp")
```

```{r}
library(rnaturalearth)
# read australia polygon
au_map = ne_states(country = 'Australia', returnclass = 'sf')
```


```{r}
# extract the geometry information
geo_road = st_geometry(au_road)
geo_state = st_geometry(au_map)

# assign each road to its corresponding state, one road can be assigned to mutiple states
roads_in_states = st_intersects(geo_state, geo_road)
dim(roads_in_states)
```

```{r}
# we want all the roads which have an intersection with VIC
VIC_roads_index = roads_in_states[[7]]
```

```{r}
# transfrom the dataset into dataframe so that we can use indexing
au_road_df = as.data.frame(au_road)

# get the roads in VIC
VIC_road = au_road_df[VIC_roads_index,]
```

```{r}
rm(geo_road)
rm(au_road)
rm(au_road_df)
rm(VIC_roads_index)
```

```{r}
gc()
memory.size()
```


```{r}
nearest_road = st_nearest_feature(temp_hotspots$geometry, VIC_road$geometry)
```

```{r}
temp$nearest_road = VIC_road$name[nearest_road]
```

```{r}
dist_vector = as.numeric(st_distance(temp_hotspots$geometry, VIC_road$geometry[nearest_road], by_element = TRUE))

temp$dist_to_road = dist_vector
```

```{r}
recreation = st_read("SDM698290\\ll_gda94\\sde_shape\\whole\\VIC\\FORESTS\\layer\\recweb_site.shp")
recreation = st_transform(recreation, crs = 4326)
```

```{r}
nearest_camp = st_nearest_feature(temp_hotspots$geometry, recreation$geometry)
```

```{r}
temp$nearest_camp = recreation$NAME[nearest_camp]

dist_vector = as.numeric(st_distance(temp_hotspots$geometry, recreation$geometry[nearest_camp], by_element = TRUE))

temp$dist_to_camp = dist_vector
```

```{r}
write.csv(temp, 'data/VIC_hotspots_OCT_MAR.csv', row.names = FALSE)
```

```{r}
test = read_csv('data/VIC_hotspots_OCT_MAR.csv')
```

```{r}
test = read_csv('data/weather.csv')
```

