---
title: "Untitled"
author: "Weihao Li"
date: "2020.06.09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidyverse)
library(raster)
library(rnaturalearth)
library(bomrang)
library(lubridate)
au_map = ne_states(country = 'Australia', returnclass = 'sf')
vic_map = au_map[7,]
```

# get fire origins

```{r}
# read in fire origins
fire_o = st_read('Data/SDM714629/ll_gda94/sde_shape/whole/VIC/FIRE/layer/fire_history_origin.shp')
```

```{r}
# filter fire from 2000
fire_o = fire_o[fire_o$FIRE_START > "2000-01-01",]
fire_o = st_transform(fire_o, crs = 4326)
temp = st_coordinates(fire_o)
fire_o$lon = temp[,1]
fire_o$lat = temp[,2]
```

```{r}
# We got 18344 obs
dim(fire_o)
```

# Join fuel layer

```{r}
# read in forest 2018
forest = raster('Data/aus_for18_publish/aus_for18_publish/aus_for18/z001001.adf')
```

```{r}
# extract coordinates information
fire_points = st_coordinates(fire_o) %>%
  as.data.frame()

# reproject to epsg:3577
fire_points = SpatialPoints(fire_points, proj4string=CRS("+init=epsg:4326")) %>%
  spTransform(projection(forest))

# extract ID of rects
fire_forest_index = extract(forest, fire_points)

# NA
not_matched = which(is.na(fire_forest_index))
```


```{r}
# 80 not matched points
length(not_matched)
ggplot()+
  geom_sf(data = vic_map)+
  geom_sf(data = fire_o[not_matched,])
```

```{r}
# access attributes
fire_forest_info = levels(forest) %>% 
  as.data.frame()

fire_forest_info = fire_forest_info %>%
  .[fire_forest_index,] %>%
  as_tibble()
```

```{r}
# join back to fire_o
for (variable in names(fire_forest_info)){
  fire_o[[variable]] = fire_forest_info[[variable]]
}
```


# Join weather data

```{r}
# read in weather data
weather = read_csv("Data/weather.csv")
weather = weather[,-1]
weather$date = make_date(year = weather$year, month = weather$month, day = weather$day)
```

```{r}
# get the 5 nearest stations
fire_o = fire_o %>%
  rowwise() %>%
  mutate(ns = list(filter(sweep_for_stations(latlon = c(lat, lon)), state == "VIC")[1:5,1]))
```

```{r}
# unlist the 5 stations
fire_o = fire_o %>%
  mutate(ns_1 = unlist(ns[1]), ns_2 = unlist(ns[2]), ns_3 = unlist(ns[3]), ns_4 = unlist(ns[4]), ns_5 = unlist(ns[5])) %>%
  select(-ns)
```

```{r}
# 18344 rows
fire_o
```

```{r}
fire_o = fire_o %>%
  mutate(ns_1 = as.numeric(ns_1), ns_2 = as.numeric(ns_2), ns_3 = as.numeric(ns_3), ns_4 =as.numeric(ns_4), ns_5 = as.numeric(ns_5))
```

```{r}
# assign unique id to each row
fire_o$ID = 1:nrow(fire_o)

# Check if the data in that station availabe
temp = fire_o %>%
  select(ID, FIRE_START, ns_1) %>%
  left_join(weather, by = c('FIRE_START' = 'date', 'ns_1' = 'station_number'))
```

```{r}
fire_o$ns_1_rainfall = !is.na(temp$rainfall)
fire_o$ns_1_temp = !is.na(temp$min_temperature)
fire_o$ns_1_solar = !is.na(temp$solar_exposure)

fire_o = fire_o %>%
  mutate(ns_rainfall = ifelse(ns_1_rainfall, ns_1, NA), ns_temp = ifelse(ns_1_temp, ns_1, NA), ns_solar = ifelse(ns_1_solar, ns_1, NA)) %>%
  select(-ns_1_rainfall,-ns_1_temp,-ns_1_solar)

```

```{r}
# check for the incompleted cases
temp2 = fire_o[!complete.cases(select(fire_o, ns_rainfall:ns_solar)),]

temp = temp2 %>%
  select(ID, FIRE_START, ns_2) %>%
  left_join(weather, by = c('FIRE_START' = 'date', 'ns_2' = 'station_number'))

temp2$ns_2_rainfall = !is.na(temp$rainfall)
temp2$ns_2_temp = !is.na(temp$min_temperature)
temp2$ns_2_solar = !is.na(temp$solar_exposure)

temp2 = temp2 %>%
  mutate(ns_rainfall = ifelse(ns_2_rainfall&is.na(ns_rainfall), ns_2, ns_rainfall), ns_temp = ifelse(ns_2_temp&is.na(ns_temp), ns_2, ns_temp), ns_solar = ifelse(ns_2_solar&is.na(ns_solar), ns_2, ns_solar)) %>%
  select(-ns_2_rainfall,-ns_2_temp,-ns_2_solar) %>%
  select(ID, ns_rainfall2 = ns_rainfall, ns_temp2 = ns_temp, ns_solar2 = ns_solar)

fire_o = left_join(fire_o, temp2, by = c('ID' = 'ID')) %>%
  mutate(ns_rainfall = ifelse(is.na(ns_rainfall), ns_rainfall2, ns_rainfall), ns_temp = ifelse(is.na(ns_temp), ns_temp2, ns_temp), ns_solar = ifelse(is.na(ns_solar), ns_solar2, ns_solar)) %>%
  select(-ns_rainfall2, -ns_temp2, -ns_solar2)
```

```{r}
# third time
temp2 = fire_o[!complete.cases(select(fire_o, ns_rainfall:ns_solar)),]

temp = temp2 %>%
  select(ID, FIRE_START, ns_3) %>%
  left_join(weather, by = c('FIRE_START' = 'date', 'ns_3' = 'station_number'))

temp2$ns_3_rainfall = !is.na(temp$rainfall)
temp2$ns_3_temp = !is.na(temp$min_temperature)
temp2$ns_3_solar = !is.na(temp$solar_exposure)

temp2 = temp2 %>%
  mutate(ns_rainfall = ifelse(ns_3_rainfall&is.na(ns_rainfall), ns_3, ns_rainfall), ns_temp = ifelse(ns_3_temp&is.na(ns_temp), ns_3, ns_temp), ns_solar = ifelse(ns_3_solar&is.na(ns_solar), ns_3, ns_solar)) %>%
  select(-ns_3_rainfall,-ns_3_temp,-ns_3_solar) %>%
  select(ID, ns_rainfall3 = ns_rainfall, ns_temp3 = ns_temp, ns_solar3 = ns_solar)

fire_o = left_join(fire_o, temp2, by = c('ID' = 'ID')) %>%
  mutate(ns_rainfall = ifelse(is.na(ns_rainfall), ns_rainfall3, ns_rainfall), ns_temp = ifelse(is.na(ns_temp), ns_temp3, ns_temp), ns_solar = ifelse(is.na(ns_solar), ns_solar3, ns_solar)) %>%
  select(-ns_rainfall3, -ns_temp3, -ns_solar3)
```

```{r}
# fourth time
temp2 = fire_o[!complete.cases(select(fire_o, ns_rainfall:ns_solar)),]

temp = temp2 %>%
  select(ID, FIRE_START, ns_4) %>%
  left_join(weather, by = c('FIRE_START' = 'date', 'ns_4' = 'station_number'))

temp2$ns_4_rainfall = !is.na(temp$rainfall)
temp2$ns_4_temp = !is.na(temp$min_temperature)
temp2$ns_4_solar = !is.na(temp$solar_exposure)

temp2 = temp2 %>%
  mutate(ns_rainfall = ifelse(ns_4_rainfall&is.na(ns_rainfall), ns_4, ns_rainfall), ns_temp = ifelse(ns_4_temp&is.na(ns_temp), ns_4, ns_temp), ns_solar = ifelse(ns_4_solar&is.na(ns_solar), ns_4, ns_solar)) %>%
  select(-ns_4_rainfall,-ns_4_temp,-ns_4_solar) %>%
  select(ID, ns_rainfall4 = ns_rainfall, ns_temp4 = ns_temp, ns_solar4 = ns_solar)

fire_o = left_join(fire_o, temp2, by = c('ID' = 'ID')) %>%
  mutate(ns_rainfall = ifelse(is.na(ns_rainfall), ns_rainfall4, ns_rainfall), ns_temp = ifelse(is.na(ns_temp), ns_temp4, ns_temp), ns_solar = ifelse(is.na(ns_solar), ns_solar4, ns_solar)) %>%
  select(-ns_rainfall4, -ns_temp4, -ns_solar4)
```

```{r}
# fifth time
temp2 = fire_o[!complete.cases(select(fire_o, ns_rainfall:ns_solar)),]

temp = temp2 %>%
  select(ID, FIRE_START, ns_5) %>%
  left_join(weather, by = c('FIRE_START' = 'date', 'ns_5' = 'station_number'))

temp2$ns_5_rainfall = !is.na(temp$rainfall)
temp2$ns_5_temp = !is.na(temp$min_temperature)
temp2$ns_5_solar = !is.na(temp$solar_exposure)

temp2 = temp2 %>%
  mutate(ns_rainfall = ifelse(ns_5_rainfall&is.na(ns_rainfall), ns_5, ns_rainfall), ns_temp = ifelse(ns_5_temp&is.na(ns_temp), ns_5, ns_temp), ns_solar = ifelse(ns_5_solar&is.na(ns_solar), ns_5, ns_solar)) %>%
  select(-ns_5_rainfall,-ns_5_temp,-ns_5_solar) %>%
  select(ID, ns_rainfall5 = ns_rainfall, ns_temp5 = ns_temp, ns_solar5 = ns_solar)

fire_o = left_join(fire_o, temp2, by = c('ID' = 'ID')) %>%
  mutate(ns_rainfall = ifelse(is.na(ns_rainfall), ns_rainfall5, ns_rainfall), ns_temp = ifelse(is.na(ns_temp), ns_temp5, ns_temp), ns_solar = ifelse(is.na(ns_solar), ns_solar5, ns_solar)) %>%
  select(-ns_rainfall5, -ns_temp5, -ns_solar5)

fire_o = fire_o %>%
  select(-(ns_1:ns_5))
```

```{r}
# join the weather infomation on that day
fire_o = left_join(fire_o, select(weather, date, station_number, rainfall, period), by = c('FIRE_START' = 'date', 'ns_rainfall' = 'station_number'))

fire_o = left_join(fire_o, select(weather, date, station_number, min_temperature, accum_days_min, max_temperature, accum_days_max), by = c('FIRE_START' = 'date', 'ns_temp' = 'station_number'))

fire_o = left_join(fire_o, select(weather, date, station_number, solar_exposure), by = c('FIRE_START' = 'date', 'ns_temp' = 'station_number'))
```

```{r}
fire_o = select(fire_o, -period, -accum_days_min, -accum_days_max)
```

```{r}
# calculate days since last rain
temp = select(fire_o, ID, FIRE_START, ns_rainfall) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_rainfall)),]

last_rain = select(temp, FIRE_START, ID)
last_rain$last_rain = NA

for (i in 0:90){
  temp2 = temp
  temp2$FIRE_START = temp2$FIRE_START - i
  
  temp3 = left_join(temp2, select(weather, date, station_number, rainfall), by = c("FIRE_START" = 'date', 'ns_rainfall' = 'station_number')) %>%
    rename(date = FIRE_START)
  
  temp3$rainfall = ifelse(is.na(temp3$rainfall), 0, temp3$rainfall)

  
  last_rain = left_join(last_rain, temp3, by = c("ID" = "ID")) %>%
    mutate(last_rain = ifelse((is.na(last_rain)) & (rainfall>0), FIRE_START - date, last_rain)) %>%
    select(ID, FIRE_START, last_rain)

}

fire_o = left_join(fire_o, select(last_rain, ID, last_rain), by = "ID")

```


```{r}
# rainfall in last 7 days
temp = select(fire_o, ID, FIRE_START, ns_rainfall) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_rainfall)),]

temp2 = temp

for (i in 1:6){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

temp2 = left_join(temp2, select(weather, station_number, date, rainfall), by = c("FIRE_START" = "date", "ns_rainfall" = "station_number")) %>%
  group_by(ID) %>%
  mutate(rainfall_7day = sum(rainfall, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-rainfall, -ns_rainfall)

fire_o = left_join(fire_o, temp2, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))

```

```{r}
# rainfall in last 14 days
temp = select(fire_o, ID, FIRE_START, ns_rainfall) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_rainfall)),]

temp2 = temp

for (i in 1:13){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

temp2 = left_join(temp2, select(weather, station_number, date, rainfall), by = c("FIRE_START" = "date", "ns_rainfall" = "station_number")) %>%
  group_by(ID) %>%
  mutate(rainfall_14day = sum(rainfall, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-rainfall, -ns_rainfall)

fire_o = left_join(fire_o, temp2, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# rainfall in last 21 days
temp = select(fire_o, ID, FIRE_START, ns_rainfall) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_rainfall)),]

temp2 = temp

for (i in 1:20){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

temp2 = left_join(temp2, select(weather, station_number, date, rainfall), by = c("FIRE_START" = "date", "ns_rainfall" = "station_number")) %>%
  group_by(ID) %>%
  mutate(rainfall_21day = sum(rainfall, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-rainfall, -ns_rainfall)

fire_o = left_join(fire_o, temp2, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# rainfall in last 28 days
temp = select(fire_o, ID, FIRE_START, ns_rainfall) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_rainfall)),]

temp2 = temp

for (i in 1:27){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

temp2 = left_join(temp2, select(weather, station_number, date, rainfall), by = c("FIRE_START" = "date", "ns_rainfall" = "station_number")) %>%
  group_by(ID) %>%
  mutate(rainfall_28day = sum(rainfall, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-rainfall, -ns_rainfall)

fire_o = left_join(fire_o, temp2, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# rainfall in last 60 days
temp = select(fire_o, ID, FIRE_START, ns_rainfall) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_rainfall)),]

temp2 = temp

for (i in 1:59){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

temp2 = left_join(temp2, select(weather, station_number, date, rainfall), by = c("FIRE_START" = "date", "ns_rainfall" = "station_number")) %>%
  group_by(ID) %>%
  mutate(rainfall_60day = sum(rainfall, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-rainfall, -ns_rainfall)

fire_o = left_join(fire_o, temp2, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# rainfall in last 90 days
temp = select(fire_o, ID, FIRE_START, ns_rainfall) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_rainfall)),]

temp2 = temp

for (i in 1:89){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

temp2 = left_join(temp2, select(weather, station_number, date, rainfall), by = c("FIRE_START" = "date", "ns_rainfall" = "station_number")) %>%
  group_by(ID) %>%
  mutate(rainfall_90day = sum(rainfall, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-rainfall, -ns_rainfall)

fire_o = left_join(fire_o, temp2, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# rainfall in last 180 days
temp = select(fire_o, ID, FIRE_START, ns_rainfall) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_rainfall)),]

temp2 = temp

for (i in 1:179){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

temp2 = left_join(temp2, select(weather, station_number, date, rainfall), by = c("FIRE_START" = "date", "ns_rainfall" = "station_number")) %>%
  group_by(ID) %>%
  mutate(rainfall_180day = sum(rainfall, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-rainfall, -ns_rainfall)

fire_o = left_join(fire_o, temp2, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# rainfall in last 360 days
temp = select(fire_o, ID, FIRE_START, ns_rainfall) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_rainfall)),]

temp2 = temp

for (i in 1:359){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

temp2 = left_join(temp2, select(weather, station_number, date, rainfall), by = c("FIRE_START" = "date", "ns_rainfall" = "station_number")) %>%
  group_by(ID) %>%
  mutate(rainfall_360day = sum(rainfall, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-rainfall, -ns_rainfall)

fire_o = left_join(fire_o, temp2, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# temp in last 7 days
temp = select(fire_o, ID, FIRE_START, ns_temp) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_temp)),]

temp2 = temp

for (i in 1:6){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

# min_temp
temp3 = left_join(temp2, select(weather, station_number, date, min_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(min_temperature_7day = min(min_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-min_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))

# max_temp
temp3 = left_join(temp2, select(weather, station_number, date, max_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(max_temperature_7day = max(max_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-max_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# temp in last 14 days
temp = select(fire_o, ID, FIRE_START, ns_temp) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_temp)),]

temp2 = temp

for (i in 1:13){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

# min_temp
temp3 = left_join(temp2, select(weather, station_number, date, min_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(min_temperature_14day = min(min_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-min_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))

# max_temp
temp3 = left_join(temp2, select(weather, station_number, date, max_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(max_temperature_14day = max(max_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-max_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# temp in last 21 days
temp = select(fire_o, ID, FIRE_START, ns_temp) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_temp)),]

temp2 = temp

for (i in 1:20){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

# min_temp
temp3 = left_join(temp2, select(weather, station_number, date, min_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(min_temperature_21day = min(min_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-min_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))

# max_temp
temp3 = left_join(temp2, select(weather, station_number, date, max_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(max_temperature_21day = max(max_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-max_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# temp in last 28 days
temp = select(fire_o, ID, FIRE_START, ns_temp) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_temp)),]

temp2 = temp

for (i in 1:27){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

# min_temp
temp3 = left_join(temp2, select(weather, station_number, date, min_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(min_temperature_28day = min(min_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-min_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))

# max_temp
temp3 = left_join(temp2, select(weather, station_number, date, max_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(max_temperature_28day = max(max_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-max_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# temp in last 60 days
temp = select(fire_o, ID, FIRE_START, ns_temp) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_temp)),]

temp2 = temp

for (i in 1:59){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

# min_temp
temp3 = left_join(temp2, select(weather, station_number, date, min_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(min_temperature_60day = min(min_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-min_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))

# max_temp
temp3 = left_join(temp2, select(weather, station_number, date, max_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(max_temperature_60day = max(max_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-max_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# temp in last 90 days
temp = select(fire_o, ID, FIRE_START, ns_temp) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_temp)),]

temp2 = temp

for (i in 1:89){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

# min_temp
temp3 = left_join(temp2, select(weather, station_number, date, min_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(min_temperature_90day = min(min_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-min_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))

# max_temp
temp3 = left_join(temp2, select(weather, station_number, date, max_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(max_temperature_90day = max(max_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-max_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```


```{r}
# temp in last 180 days
temp = select(fire_o, ID, FIRE_START, ns_temp) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_temp)),]

temp2 = temp

for (i in 1:179){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

# min_temp
temp3 = left_join(temp2, select(weather, station_number, date, min_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(min_temperature_180day = min(min_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-min_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))

# max_temp
temp3 = left_join(temp2, select(weather, station_number, date, max_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(max_temperature_180day = max(max_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-max_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```


```{r}
# temp in last 360 days
temp = select(fire_o, ID, FIRE_START, ns_temp) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_temp)),]

temp2 = temp

for (i in 1:359){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}

# min_temp
temp3 = left_join(temp2, select(weather, station_number, date, min_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(min_temperature_360day = min(min_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-min_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))

# max_temp
temp3 = left_join(temp2, select(weather, station_number, date, max_temperature), by = c("FIRE_START" = "date", "ns_temp" = "station_number")) %>%
  group_by(ID) %>%
  mutate(max_temperature_360day = max(max_temperature, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-max_temperature, -ns_temp)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```


```{r}
# solar exposure in last 7 days
temp = select(fire_o, ID, FIRE_START, ns_solar) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_solar)),]

temp2 = temp

for (i in 1:6){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}


temp3 = left_join(temp2, select(weather, station_number, date, solar_exposure), by = c("FIRE_START" = "date", "ns_solar" = "station_number")) %>%
  group_by(ID) %>%
  mutate(solar_exposure_7day = sum(solar_exposure, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-solar_exposure, -ns_solar)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# solar exposure in last 14 days
temp = select(fire_o, ID, FIRE_START, ns_solar) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_solar)),]

temp2 = temp

for (i in 1:13){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}


temp3 = left_join(temp2, select(weather, station_number, date, solar_exposure), by = c("FIRE_START" = "date", "ns_solar" = "station_number")) %>%
  group_by(ID) %>%
  mutate(solar_exposure_14day = sum(solar_exposure, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-solar_exposure, -ns_solar)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# solar exposure in last 21 days
temp = select(fire_o, ID, FIRE_START, ns_solar) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_solar)),]

temp2 = temp

for (i in 1:20){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}


temp3 = left_join(temp2, select(weather, station_number, date, solar_exposure), by = c("FIRE_START" = "date", "ns_solar" = "station_number")) %>%
  group_by(ID) %>%
  mutate(solar_exposure_21day = sum(solar_exposure, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-solar_exposure, -ns_solar)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# solar exposure in last 28 days
temp = select(fire_o, ID, FIRE_START, ns_solar) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_solar)),]

temp2 = temp

for (i in 1:27){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}


temp3 = left_join(temp2, select(weather, station_number, date, solar_exposure), by = c("FIRE_START" = "date", "ns_solar" = "station_number")) %>%
  group_by(ID) %>%
  mutate(solar_exposure_28day = sum(solar_exposure, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-solar_exposure, -ns_solar)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# solar exposure in last 60 days
temp = select(fire_o, ID, FIRE_START, ns_solar) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_solar)),]

temp2 = temp

for (i in 1:59){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}


temp3 = left_join(temp2, select(weather, station_number, date, solar_exposure), by = c("FIRE_START" = "date", "ns_solar" = "station_number")) %>%
  group_by(ID) %>%
  mutate(solar_exposure_60day = sum(solar_exposure, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-solar_exposure, -ns_solar)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# solar exposure in last 90 days
temp = select(fire_o, ID, FIRE_START, ns_solar) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_solar)),]

temp2 = temp

for (i in 1:89){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}


temp3 = left_join(temp2, select(weather, station_number, date, solar_exposure), by = c("FIRE_START" = "date", "ns_solar" = "station_number")) %>%
  group_by(ID) %>%
  mutate(solar_exposure_90day = sum(solar_exposure, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-solar_exposure, -ns_solar)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# solar exposure in last 180 days
temp = select(fire_o, ID, FIRE_START, ns_solar) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_solar)),]

temp2 = temp

for (i in 1:179){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}


temp3 = left_join(temp2, select(weather, station_number, date, solar_exposure), by = c("FIRE_START" = "date", "ns_solar" = "station_number")) %>%
  group_by(ID) %>%
  mutate(solar_exposure_180day = sum(solar_exposure, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-solar_exposure, -ns_solar)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
# solar exposure in last 360 days
temp = select(fire_o, ID, FIRE_START, ns_solar) %>% 
  .[complete.cases(select(fire_o, ID, FIRE_START, ns_solar)),]

temp2 = temp

for (i in 1:359){
  temp3 = temp
  temp3$FIRE_START = temp3$FIRE_START - i
  
  temp2 = bind_rows(temp2, temp3)
}


temp3 = left_join(temp2, select(weather, station_number, date, solar_exposure), by = c("FIRE_START" = "date", "ns_solar" = "station_number")) %>%
  group_by(ID) %>%
  mutate(solar_exposure_360day = sum(solar_exposure, na.rm = TRUE)) %>%
  ungroup() %>%
  select(-solar_exposure, -ns_solar)

fire_o = left_join(fire_o, temp3, by = c("ID" = "ID", "FIRE_START" = "FIRE_START"))
```

```{r}
st_write(fire_o, 'training.shp')
```

```{r}
fire_o = st_read("training.shp")
```

```{r}
fire_o %>%
  as_tibble()
```

```{r}
cfa = st_read("Data/SDM697752/ll_gda94/sde_shape/whole/VIC/VMFEAT/layer/geomark_point.shp")
```

```{r}
cfa = cfa %>% filter(FEATSUBTYP == "fire station")
```

```{r}
cfa = st_transform(cfa, crs = 4326)
```


```{r}
nearest_index = st_nearest_feature(fire_o$geometry, cfa$geometry)
temp = st_distance(fire_o$geometry, cfa$geometry[nearest_index], by_element = TRUE)
fire_o$dist_cfa = as.numeric(temp)
rm(cfa)
```

```{r}
camp = st_read("Data/SDM698290/ll_gda94/sde_shape/whole/VIC/FORESTS/layer/recweb_site.shp")
```

```{r}
camp = st_transform(camp, crs = 4326)
nearest_index = st_nearest_feature(fire_o$geometry, camp$geometry)
temp = st_distance(fire_o$geometry, camp$geometry[nearest_index], by_element = TRUE)
fire_o$dist_camp = as.numeric(temp)
rm(camp)
```

```{r}
road = st_read("Data/australia-latest-free.shp/gis_osm_roads_free_1.shp")
```

```{r}
roads_in_vic = st_intersects(vic_map$geometry, road$geometry)
road = road[roads_in_vic[[1]],]
```

```{r}
nearest_index = st_nearest_feature(fire_o$geometry, road$geometry)
temp = st_distance(fire_o$geometry, road$geometry[nearest_index], by_element = TRUE)
fire_o$dist_road = as.numeric(temp)
rm(road)
```

```{r}
st_write(fire_o, "training2.shp")
```



