---
title: "EDA"
author: "Weihao Li"
date: "2020.06.23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(tidyverse)
library(rnaturalearth)
library(lubridate)
library(ggmosaic)
au_map = ne_states(country = 'Australia', returnclass = 'sf')
vic_map = au_map[7,]
```

```{r}
fire_o = st_read("training2.shp")
```

```{r}
fire_o = fire_o[fire_o$FOR_CAT != 'Non forest',]
fire_o = fire_o[!is.na(fire_o$CAUSE),]
```

```{r}
fire_o$CAUSE %>% levels()
```

```{r}
fire_o = fire_o %>%
  mutate(new_cause = ifelse(CAUSE == "DELIBERATE LIGHTING (MALICIOUS)", "arson", NA)) %>%
  mutate(new_cause = ifelse(CAUSE == "LIGHTNING", "lightning", new_cause)) %>%
  mutate(new_cause = ifelse(is.na(new_cause), "other", new_cause))
```

```{r}
fire_o %>% names()
```

```{r}
fire_o %>% as_tibble()
```


```{r}
fire_o$new_cause %>% as.factor() %>% summary()
```


```{r}
temp = select(fire_o, rainfll:dist_road, new_cause, HEIGHT, COVER, FOR_COD, FIRE_STAR) %>%
  mutate(log_dist_road = log(dist_road)) %>%
  mutate(log_dist_cfa = log(dist_cfa)) %>%
  mutate(log_dist_camp = log(dist_camp))
plots = list()
j = 0

for (i in names(temp)){
  
  if (i %in% c("HEIGHT", "COVER")){
    j = j + 1
    plots[[j]] = ggplot(temp) + 
    geom_mosaic(aes_string(x = paste0('product(',i,')'),fill='new_cause'))+
    xlab(i)+
    ylab("cause")
    next
  }
  
  if (i %in% c("FOR_COD")){
    j = j + 1
    plots[[j]] = temp %>%
      filter(FOR_COD %in% head(arrange(count(temp, FOR_COD), desc(n)), 10)[['FOR_COD']]) %>%
      mutate(FOR_COD = factor(FOR_COD)) %>%
      ggplot() + 
    geom_mosaic(aes_string(x = paste0('product(',i,')'),fill='new_cause'))+
    xlab(i)+
    ylab("cause")
    next
  }
  
  if (!(i %in% c("geometry", "new_cause", "FIRE_STAR"))){
    j = j + 1
    plots[[j]] = ggplot(temp) +
      geom_density(aes_string(i, color = 'new_cause'))
  }
  
}

plots
```

```{r}
library(randomForest)
```
```{r}
temp = select(as_tibble(fire_o), rainfll:dist_road, HEIGHT, COVER, FOR_COD, new_cause) %>%
  complete.cases()
temp = select(as_tibble(fire_o), rainfll:dist_road, HEIGHT, COVER, FOR_COD, new_cause) %>%
  mutate(log_dist_road = log(dist_road)) %>%
  mutate(log_dist_cfa = log(dist_cfa)) %>%
  mutate(log_dist_camp = log(dist_camp)) %>%
  select(-dist_road, -dist_cfa, -dist_camp) %>%
  mutate(new_cause = factor(new_cause)) %>%
  mutate(HEIGHT = factor(HEIGHT)) %>%
  mutate(COVER = factor(COVER)) %>%
  mutate(FOR_COD = factor(FOR_COD)) %>%
  .[temp,]


rmod = randomForest(x = select(temp, -new_cause), y = temp$new_cause, ntree = 2000)
```

```{r}
rmod

```


```{r}
rmod$confusion
```


```{r}
mmod = nnet::multinom(new_cause~., data = temp, maxit = 1000)
```

```{r}
summary(mmod)
```

```{r}
library(caret)

confusionMatrix(predict(mmod), temp$new_cause)
```
```{r}
confusionMatrix(rmod$predicted, temp$new_cause)
```

```{r}
rmod$importance
```

```{r}
library(tourr)
if(Sys.getenv("RSTUDIO") == "1" & # check if running in RStudio
       .Platform$OS.type == "unix") quartz() else X11()
animate_xy(select(temp, -HEIGHT, -COVER, -FOR_COD, -new_cause), col = temp$new_cause)
```

