---
knit: "bookdown::render_book"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, cache=TRUE)
# Load any R packages you need here
library(tidyverse)
```

# Abstract {-}

The 2019-2020 Australian bushfire season had a devastating impact on the environment, buildings and properties. Debate about the cause of the bushfires was fierce. Social media was peppered with claims of arson, while climate change studies have suggested that hotter drier conditions increase susceptibility to fires ignited by lightning strikes. Historical bush fire origins data, collected over 2000-2018, has labelled causes of a comprehensive collection of fire. The availability of remote sensing hotspot data provides an opportunity to detect fires almost in real-time. We developed a spatio-temporal clustering algorithm to detect the time and locations of bushfire ignition from this hotspot data. Both historical data and hotspot detected fire ignitions data are supplemented with data on weather conditions leading up to the fires, vegetation type, proximity to roads, camp sites, and fire stations. The historical data is used to train a random forest model to classify the cause, which is used to predict the cause of bushfire ignitions detected from hotspot data in Victoria during the 2019-2020 season. The final model showed good predictive ability with 74.95% overall accuracy, and 90.5% accuracy in lightning-caused bushfires. The primary cause for 2019-2020 Victoria bushfire ignitions using the model found that lightning was the major cause (82%), with arson responsible for just 3.62% of the total fires. The clustering algorithm and the predictive model developed in this research could help fire authorities to more readily monitor and investigate bushfire risk and causes using satellite hotpot data.

*Key words: machine learning, statistics, spatio-temporal data, cluster analysis, data visualization, exploratory data analysis, data science*


<!-- The main points of the abstract will be: -->

<!-- 1. Background and motivation (Why did we do this research and what did we research) -->
<!-- 2. Mention we developed an algorithm, and what is its main usage -->
<!-- 3. Mention we fitted a random forest model to the historical ignition data -->
<!-- 4. What was the model performance -->
<!-- 5. Mention we predicted the causes of 2019-2020 Australia bushfire using this model -->
<!-- 6. The major finding in the prediction -->
<!-- 7. One main contribution -->

