---
chapter: 2
knit: "bookdown::render_book"
---

# Introduction {#ch:introduction}

## 2019-2020 Australia bushfires

In Australia, bushfires have historically caused massive loss of property and life. Since the 1967 Hobart bushfires, insurance claims for building losses have exceeded 10 million Australia dollars [@mcaneney2009100]. The 2019-2020 Australia bushfires had a more devastating impact on the environment and property compared with other major bushfires in history.  According to a report by @LisaRichardsNigelBrew2020 published by the Parliament of Australia, 3094 houses were destroyed and over 17M hectares of land burned. These two figures represent the greatest in history. Fortunately, fewer lives were lost: 33 (including firefighters) compared to 173 in the 2009 Black Saturday fires and 47 in 1983 Ash Wednesday fires [@LisaRichardsNigelBrew2020].

Debate about the cause of this crisis was a focal point on social media at the beginning of the bushfire season. Some argued that climate change had a major impact on the catastrophic and unprecedented bushfires. They used hastag *#ClimateEmergency* on Twitter to convey their beliefs and promote action on climate change [@graham2020bushfires]. Climate Council, one of the biggest climate organizations in Australia made up of climate scientists and experts, claimed that climate change not only worsened the bushfire season but also increased the cost of fighting fires [@council2019not]. Meanwhile, in the first few weeks of 2020, another group presented a completely different argument and claimed the cause of this bushfire season was arson instead of climate change. They attempted to overtake the *#ClimateEmergency* hashtag with the *#ArsonEmergency* hashtag [@graham2020bushfires]. Although police [@knausc2020bushfires] contradicted this controversial claim immediately, the spread of this theory did not slow down at all. Research conducted by Dr. Timothy Graham and Dr. Tobias R. Keller [-@graham2020bushfires] from the Queensland University of Technology assessed around 300 Twitter accounts driving the *#ArsonEmergency* hashtag and found that a third of them were suspicious due to automated and inauthentic behaviour. They believed that the accounts were very likely run by disinformation campaigns. However, there was no direct evidence to support this hypothesis, particularly without knowledge of the owners of the accounts. 

There is limited information on the cause of this catastrophic hazard in 2019-2020 [@LisaRichardsNigelBrew2020]. Bushfire investigation usually takes a certain amount of time and the result is not guaranteed. According to Beale and Jones's work [-@beale2011preventing], the cause is known for only 58.9% of fires in history. Among the known cases, about 50% are due to suspicious and deliberate ignitions, 35% by accidents, and 6% by natural causes such as lightning. There is considerable variation in rates due to location, time, and difficulties of counting fire origins in a bushfire season.

Understanding the cause of 2019-2020 Australia bushfires may provide some help in developing effective strategies for mitigating bushfire impact. If the majority of bushfires are ignited by lightning, fuel management such as planned burns could be delivered more often and at a larger scale. Alternatively, if arson plays an important role in the ignitions, improvements in public legal education and research on environmental criminology may be required.


## Remote sensing data

Remote sensing data are collected by remote sensors carried by a satellite or an aircraft. These sensors can detect energy reflected from the earth and record it as signals [@schowengerdt2006remote], which are then sent back to the Mission Control Center on the ground for further processing and the development of high-quality products, such as high-resolution colour images of Earth and sea surface temperature maps.

Contributing to the problem is that many bushfires start in very remote areas -- locations deep into the temperate forests ignited by lightning -- that are virtually impossible to access or to monitor. Remote sensing data, particularly satellite hotspot data, provide a possible solution to this challenge and may be useful in detecting ignitions and movement of bushfires. Newly available hotspot data collected from the Himawari-8 satellite [@jaxa] has a 10-minute time resolution that could be used to detect fires almost in real-time.

Knowing the precise ignition location and ignition time allows us to reconstruct detailed information about conditions at the time of a fire's start, such as weather and distribution of vegetation. This may be helpful in understanding the cause of bushfires.


## Research objectives and contribution

<!--

This research explore the potential methods of fire ignition during 2019-2020 Australia bushfires season based on the new availability of satellite data. Satellite data provides the opportunity to more objectively study ignition locations, particularly in less accessible regions.

The overall research aim is to provide probabilistic estimates of the cause of fire ignition for the 2019-2020 bushfires. Several smaller research questions that being addressed are:

  1. Using satellite hotspots data can we detect ignition time and location? 
  2. How do the characteristics of 2019-2020 bushfires compare to historical bushfires?
  3. Can data from other sources including vegetation, weather, proximity to road and recreation sites help to inform ignition type?

-->

The overall objectives of this research are to (i) develop an algorithm to detect time and location of ignitions for the 2019-2020 Australia bushfires in Victoria from satellite hotspot data, and (ii) build a predictive model to classify the potential causes of bushfire ignitions. 


Clustering algorithms represent an unsupervised learning method to collect similar data points into the same group. To organize satellite hotspot data, this research proposes a spatio-temporal clustering algorithm inspired by two existing clustering algorithms, Density Based Spatial Clustering of Applications with Noise (**DBSCAN**) [@ester1996density] and Fire Spread Reconstruction (**FSR**) [@loboda2007reconstruction]. 

The core functionality of our clustering algorithm determines whether a hotspot is a new ignition point or a branch of an existing bushfire. This requires that the algorithm runs recursively in a temporal manner with reference to the bushfire dynamics. In contrast to traditional spatio-temporal clustering algorithms [@kisilevich2009spatio], our algorithm slices the data by its temporal dimension and therefore divides the overall spatio-temporal clustering task into thousands of spatial clustering tasks. The final clustering results are obtained by combining membership information in different timestamps. This design overcomes one of the issues in defining the data space in traditional spatio-temporal clustering algorithms; the scaling of the temporal dimension can be highly influential to the clustering result [@kisilevich2009spatio]. Additionally, our algorithm reconstructs clusters in parallel, and therefore mitigates the fire merging issue in the **FSR** algorithm. Other than that, since parameter tuning is not available in the **FSR** algorithm, a visualization tool is designed to enable us to choose near-optimal values of parameters. 

In essence, our algorithm clusters hotspots into bushfires with arbitrary shape and size, which can help track the movement, coverage and intensity of every bushfire. Meanwhile, it provides an automatic process to detect new bushfire ignitions from the satellite hotspot data, which may be beneficial for urgent fire resource planning and deployment to remote areas in the future. Importantly, by applying this algorithm on satellite hotspot data from the past bushfire season, we are able to reconstruct fire events to enrich our knowledge of bushfire behaviour.


The general choice for bushfire modelling is the generalised additive model (**GAM**). For example, @read2018lightning used **GAM** to model the risk of lightning-caused bushfires in Victoria. In this research, a spectrum of statistical models are explored as the classifier to predict the cause of the bushfire ignition, including **GAM**, as well as other computationally intensive models that are popular in the field of modern machine learning but rarely used in bushfire modelling. Our final model can be used to produce predictions of the cause of 2019-2020 Australia bushfires in Victoria. To our knowledge, there is not yet any academic research on modelling and predicting the cause of this bushfire season.


Overall, this research offers a complete workflow for bushfire analysis and monitoring, starting with the detection of bushfire ignitions from satellite hotspot data, through the production of predictions of the cause of these ignitions. We believe this workflow can be adopted into future bushfire investigation, particularly to establish the cause of bushfires.


## Scope of the thesis

This thesis focuses on analysing 2019-2020 bushfires in Victoria with open-source remote sensing data. The remainder of the thesis is structured as follows. In chapter 2, we review the existing literature in the relevant fields. In chapter 3, we outline the data source and data integration, and provide a brief data exploratory analysis of the compiled datasets. In chapter 4, we describe the clustering algorithm and present the clustering results. In chapter 5, we outline the strategy of model building and discuss the results we found. In chapter 6, we discuss limitations of our work and possible future extensions. Finally, in chapter 7, we give a brief conclusion of the research. 





