---
chapter: 3
knit: "bookdown::render_book"
---

# Review of literature {#ch:rol}

## Spatio-temporal clustering

To detect time and location of the bushfire ignitions from the satellite hotspot data, hotspots need to be grouped into meaningful clusters. This can be achieved by using spatio-temporal clustering.

Spatio-temporal data contain at least three dimensions, which are spatial location (e.g. latitude and longitude) and time. In the survey of spatio-temporal clustering algorithms, @kisilevich2009spatio summarised that there are five types of point-wise spatio-temporal data, including spatio-temporal events, geo-referenced variable, geo-referenced time series, moving points and trajectories. Table \ref{tab:st} shows that the classification of data is based on their temporal and spatial dimensions. 

(ref:sttable) A classification of spatio-temporal point-wise data types [@kisilevich2009spatio]

```{r}
library(tidyverse)
library(kableExtra)
data.frame(single = c("Spatio-temporal events", ""), updated = c("Geo-referenced variable", "Moving points"), time = c("Geo-referenced time series", "Trajectories")) %>%
  `rownames<-`(c('Fixed locatoin', 'Dynamic location')) %>%
  knitr::kable(format = "latex", 
               col.names = c("Single snapshot", "Updated snapshot", "Time series"),
               label = 'st',
               caption = "(ref:sttable)",
               booktabs = TRUE) %>%
  kableExtra::kable_styling(latex_options = c("scale_down"))
```

Meanwhile in satellite hotspots clustering, the data type is even more complicated. Each moving object possesses a spatial extension with arbitrary size and shape [@kisilevich2009spatio]. 

Before performing the clustering algorithm on spatio-temporal data, deciding how to represent the temporal information in a high-dimensional space is challenging [@kisilevich2009spatio]. This is because the end result of the clustering algorithm can be highly sensitive to the temporal resolution. Hence, scaling of the temporal dimension varies by application.

In the late '90s, researchers in the University of Munich proposed an influential density-based algorithm, Density Based Spatial Clustering of Applications with Noise (**DBSCAN**), for discovering clusters [@ester1996density]. @ester1996density mentioned three difficulties of clustering algorithms which motivated their work: (1) requirements of domain knowledge to determine the hyperparameters, (2) arbitrary shape of clusters and (3) computational efficiency. 

**DBSCAN** defines a maximum radius $\epsilon$ to construct densities around each point, which are spheres in the case of 3-dimensional space. To overcome the impact of noise, at least a minimum number of points (`MinPts`) are contained by the sphere. Finally, intersected spheres are considered to belong to the same cluster. 

The time complexity of **DBSCAN** is $O(N log(N))$, and the memory complexity is only $O(N)$. By visualizing the density of distance to the k-th nearest neighbour from each point, optimal values of $\epsilon$ and `MinPts` can be chosen.
 
Although **DBSCAN** is popular among many fields, it is not suitable for clustering hotspot data. First, it does not address the issue of defining the scaling of the temporal dimension. Second, the behaviour of bushfires is not taken into account. The **DBSCAN** algorithm assumes the clustering rules work in both directions of a timeline, which does not capture the reality that bushfires evolve over time in one direction.

A better algorithm for satellite hotspots clustering is Fire Spread Reconstruction (**FSR**) [@loboda2007reconstruction]. This algorithm starts from the earliest observed hotspot. It constructs a tree based on three rules: (1) the earliest observed hotspot is the root of the tree, (2) any node is within a 2.5km radius from its parent and (3) any node is observed no later than four days from its parent. When the tree is closed and there are still unassigned hotspots, the algorithm continues at the earliest unassigned hotspot to construct a new tree. Finally, each tree is a cluster, and the earliest hotspot is defined as the ignition point.

**FSR** works well in reconstructing bushfire spread, but it constructs clusters sequentially. If two fires start at a different locations but have overlapping coverage, **FSR** considers them to be a single fire when they meet each other. In this situation, the coverage of one of the fires increases dramatically during a short period of time, which does not correctly reflect the real speed of the bushfire. Besides, @loboda2007reconstruction did not provide details of parameter tuning in their research. Instead, they briefly delivered the reason for choosing four days as the time threshold, which was because they wanted to tolerate missing observations due to cloud and smoke cover.

**DBSCAN** is mature and efficient with a parameter tuning tool, but is not suitable for temporal data like satellite hotspot data. **FSR** is designed for satellite hotspot data but lacks detailed consideration of parameter tuning and fire interactions. Inspired by these two algorithms, our work designs a spatio-temporal algorithm that can efficiently and robustly cluster hotspots with respect to the temporal behaviour of bushfires. Meanwhile, we provide a tool to help make parameter choices.


## Bushfire modelling

Existing research on bushfire modelling can be divided into two main categories: simulation and analytical modelling. 

In simulation modelling, @keane2004classification developed landscape fire succession models (LFSMs) to simulate spatial fire behaviour, including fire ignition and fire spread, that accounted for fire and vegetation dynamics. @bradstock2012wildfires used a model called **FIRESCAPE** which involved simulating fire behaviours with fuel and weather conditions. Simulation methods are cost- and time-effective ways to model bushfires, but ignition cause is not considered [@clarke2019developing].  These methods seldom address the ignition methods that we are interested in. <!--Therefore, simulation modelling will not be considered in our bushfire ignition research.--> 

Analytical modelling is another common way to build bushfires models. A commonly used modelling framework for analysing bushfire ignition is the generalised additive model (**GAM**). @bates2018exploratory used this model with a Gaussian distribution to predict the number of lightning ignitions in Warren Region, Western Australia. Some studies implemented **GAM** with a binomial distribution to predict ignition probabilities in New South Wales, Australian Capital Territory and Victoria [@read2018lightning;@zhang2017wildfire]. Mixed-effect models are an alternative to incorporate spatial dependence and weather factors. @duff2018dryness showed that by treating drought factor and intercept as random effects, and forest type as a grouping variable, a mixed-effect model with only three variables achieved 70% mean accuracy to predict fire occurrence in Southern Australia. Simpler parametric models have also been widely used, including multiple linear regression, negative binomial regression and generalised logistic regression [@cheney2012predicting;@plucinski2014predicting;@collins2015spatial]. Instead of modelling bushfires, some researchers conducted statistical tests and exploratory methods to assess hypotheses about bushfires [@miller2017electrically;@dowdy2017pyrocumulonimbus].

Common covariates for bushfire ignition analysis are weather conditions, vegetation types, topographic information and the environmental impact of human activities. In addition, various fire danger indices have been used in modelling. Some studies chose to use index variables developed by McArthur, such as the Forest Fire Danger Index [@clarke2019developing;@read2018lightning], while others chose to use indices developed by the Canadian Forestry Service, such as Canadian Fire Weather Index and Drought Code [@plucinski2014predicting]. We question the usefulness of these indices for bushfire ignition analysis since they are mostly extracted from weather and vegetation information. Comparing the paper written by @zumbrunnen2012human to the authors' previous work -@zumbrunnen2011weather on the same topic, the fire weather index was replaced with temperature and precipitation for climate proxies, as the latter were available for the entire study period. Similarly, fire weather indices are not be considered in our research given that we have access to climate and vegetation data.

Throughout review of the existing literature, we have not found any research that attempts to model the cause of the bushfires in Australia, nevermind doing so with hotspot data. Therefore, we build a model by incorporating parts of the modelling framework and covariate choices mentioned above, and we use hotspot data to predict the cause of bushfires in Victoria during the 2019-2020 season.

Although numerous studies for ignition analysis have applied semi-parametric and parametric methods, little use of machine learning models has been made. From a predictive modelling perspective, exploiting modern algorithms to obtain better prediction performance is vital. Hence, these approaches are considered for this research.

Most of the existing work on bushfire ignition focuses on fewer than three states in Australia and models are rarely applied to all of Australia. This is mainly due to the lack of coherence in bushfire datasets provided by different states in Australia. For the same reason, we only focus on bushfires in Victoria in this research.



