---
chapter: 7
knit: "bookdown::render_book"
---

# Discussion and conclusion {#ch:discussion}

In conclusion, we develop a spatio-temporal clustering algorithm for detecting bushfire ignitions from satellite hotspot data, which provides an alternative method to collect bushfire ignition data besides field observation. We present a random forest model for classifying the cause of bushfire ignitions in Victoria, which demonstrates good predictive power (79% overall accuracy and 0.8795 mult-class AUC). Wind speed, latitude, proximity to the nearest fire station, proximity to the nearest recreation site and proximity to the nearest road show high influence to the predicted probability. The prediction of the cause of bushfire ignitions in Victoria during the 2019-2020 season produced by the predictive model suggests the main cause is lightning (82%). Availability of satellite hotspot data and supplementary open data make it possible to deploy the clustering algorithm and the predictive model used in this research, which could benefit bushfire investigation of past and future events and real-time bushfire monitoring. 


## Policy Implications

Our prediction suggests that the main cause of the 2019-2020 Australia bushfires is lightning. According to the clustering results, these bushfires are mostly start in remote areas, like East Gippsland. Our fire risk map gives similar result that indicates east of Victoria in January is at high risk of lightning-caused bushfire. We suggest the Forest Fire Management Victoria and the Country Fire Authority to consider delivering planned burns on a larger scale in these regions in an earlier date ahead of the bushfire season. Smoke and pollution to the environment produced by the planned burns are unavoidable, but it is considerably better than the uncontrollable bushfires. Meanwhile, modern technology for monitoring and fighting bushfires like satellite sensors, community sensors and drones could be deployed in these areas to overcome the difficulties of reaching the ignition point. Budgets on bushfire prevention need to increase if possible, or at least, distribute heavier to these areas to employ more firefighters during the bushfire season. 

Besides, according to our prediction, the number of accident-caused bushfires rises significantly in March 2020. We suspect they are correlated to certain types of human activities or weather conditions. Bushfire investigators in Country Fire Authority may need to reveal the motivations behind this phenomenon to reduce this controllable impact on bushfire ignition.


Finally, future bushfire investigation could be performed more concisely by utilising satellite hotspots data and modern machine learning framework. We have shown this is achievable and we suggest the government could spend some resources on developing a set of reliable and accurate models to predict the cause of the bushfire ignition remotely by fusing the available data, the knowledge of climate scientists and the experience of investigators. This could overcome the workforce shortage and reduce the countless time spent on the investigation.

 

## Limitation and possible extensions

### Data

In this research, vegetation dynamics has not been taken into account in modelling. Instead, a static map of vegetation information is used. This could lead to ineffective use of vegetation factors. A possible future direction will be incorporating vegetation data collected in multiple years. 

In the prediction of 2019-2020 season, **ASOS** wind speed data is used as covariate. **ASOS** network only has a limited number of stations in Victoria, so the weather conditions integrated to estimated bushfire ignitions could be inaccurate. To improve the accuracy of the prediction, **BOM** wind speed data can be used in the future, but they are not publicly available.

### Clustering algorithm

During the reconstruction of the bushfire dynamics, only satellite hotspot data is used in our clustering algorithm. Other influential factors such as distribution of vegetation, slope and weather conditions have not been taken into account. These factors will affect the speed of the bushfire and the direction of the spread. An extension that we plan to pursue is a more comprehensive and complicated algorithm that allows variable speed of bushfire and variable time tolerance during the clustering. 

### Modelling

Only 4 statistical models have been tested in this research. Other popular machine learning models such as artificial neural network and support vector machine may have a better performance. However, these modelling frameworks typically require significant amount of time in hyperparameter tuning. Besides, advanced modelling techniques like model fusion and dimensionality reduction can be applied to this problem in future work.

### Fire risk map

We show the use of our predictive model in producing the fire risk map. However, a simple method is used to estimate the probability of at least one bushfire ignited in a given region and in a given month. None of the changes of the distribution of vegetation and differences in the weather conditions have been considered. In the future work, we will develop another model to provide accurate prediction of the risk of the bushfire ignition $P(S|\mathcal{F})$. Combining the outcomes of two models, we will eventually be able to produce the precise risk of bushfire ignited by different methods $P(M, S|\mathcal{F})$.

### Shiny app

General public and officers from fire departments may not have time and capability in running the code of our predictive model. An interactive web-based shiny application could be a more accessible way for people to benefit from our research. It could provide elegant interactive plots for exploratory data analysis and real-time prediction for decision making in bushfire management. A shiny app is under development by @shiny-app. The product will be published on the server of the Department of Econometrics and Business Statistics, Monash University recently. An early stage release can be found on https://ebsmonash.shinyapps.io/VICfire/.





