---
knit: "bookdown::render_book"
---

\appendix

# Covariate information

\footnotesize

```{r}
datasets_info = data.frame(index = c(
                                     "month",
                                     "day",
                                     "dow",
                                     "lon",
                                     "lat",
                                     "FOR_TYPE",
                                     "COVER",
                                     "HEIGHT",
                                     "rf",
                                     "rf7",
                                     "arf14",
                                     "arf28",
                                     "arf60",
                                     "arf90",
                                     "arf180",
                                     "arf360",
                                     "arf720",
                                     "se",
                                     "ase7",
                                     "ase14",
                                     "ase28",
                                     "ase60",
                                     "ase90",
                                     "ase180",
                                     "ase360",
                                     "ase720",
                                     "maxt",
                                     "amaxt7",
                                     "amaxt14",
                                     "amaxt28",
                                     "amaxt60",
                                     "amaxt90",
                                     "amaxt180",
                                     "amaxt360",
                                     "amaxt720",
                                     "mint",
                                     "amint7",
                                     "amint14",
                                     "amint28",
                                     "amint60",
                                     "amint90",
                                     "amint180",
                                     "amint360",
                                     "amint720",
                                     "ws",
                                     "aws_m0",
                                     "aws_m1",
                                     "aws_m3",
                                     "aws_m6",
                                     "aws_m12",
                                     "aws_m24",
                                     "log_dist_cfa",
                                     "log_dist_camp",
                                     "log_dist_road"),
                           name = c(
                                    "Month",
                                    "Day",
                                    "Day of the week. 1-7",
                                    "Longitude",
                                    "Latitude",
                                    "Forest type. Eg. Acacia, Callitris, Casuarina, etc.",
                                    "Forest crown cover. 1-6. Check COVER look up table",
                                    "Forest height class. 1-6. Check HEIGHT look up table",
                                    "Rainfall on that day",
                                    "Average rainfall in the past 7 days",
                                    "Average rainfall in the past 14 days",
                                    "Average rainfall in the past 28 days",
                                    "Average rainfall in the past 60 days",
                                    "Average rainfall in the past 90 days",
                                    "Average rainfall in the past 180 days",
                                    "Average rainfall in the past 360 days",
                                    "Average rainfall in the past 720 days",
                                    "Global solar exposure on that day",
                                    "Average global solar exposure in past 7 days",
                                    "Average global solar exposure in past 14 days",
                                    "Average global solar exposure in past 28 days",
                                    "Average global solar exposure in past 60 days",
                                    "Average global solar exposure in past 90 days",
                                    "Average global solar exposure in past 180 days",
                                    "Average global solar exposure in past 360 days",
                                    "Average global solar exposure in past 720 days",
                                    "Maximum temperature on that day",
                                    "Average maximum temperature in the past 7 days",
                                    "Average maximum temperature in the past 14 days",
                                    "Average maximum temperature in the past 28 days",
                                    "Average maximum temperature in the past 60 days",
                                    "Average maximum temperature in the past 90 days",
                                    "Average maximum temperature in the past 180 days",
                                    "Average maximum temperature in the past 360 days",
                                    "Average maximum temperature in the past 720 days",
                                    "Minimum temperature on that day",
                                    "Average minimum temperature in the past 7 days",
                                    "Average minimum temperature in the past 14 days",
                                    "Average minimum temperature in the past 28 days",
                                    "Average minimum temperature in the past 60 days",
                                    "Average minimum temperature in the past 90 days",
                                    "Average minimum temperature in the past 180 days",
                                    "Average minimum temperature in the past 360 days",
                                    "Average minimum temperature in the past 720 days",
                                    "Average wind speed on that day",
                                    "Average wind speed on that month",
                                    "Average wind speed in last month",
                                    "Average wind speed in last 3 months",
                                    "Average wind speed in last 6 months",
                                    "Average wind speed in last 12 months",
                                    "Average wind speed in last 24 months",
                                    "Natural logarithm of the distance to the nearest CFA station",
                                    "Natural logarithm of the distance to the nearest recreation site",
                                    "Natural logarithm of the distance to the nearest road"), 
                           type = c(
                                     "",
                                     "",
                                     "",
                                     "degrees",
                                     "degrees",
                                     "",
                                     "",
                                     "",
                                     "mm",
                                     "mm",
                                     "mm",
                                     "mm",
                                     "mm",
                                     "mm",
                                     "mm",
                                     "mm",
                                     "mm",
                                     "MJ/m^2",
                                     "MJ/m^2",
                                     "MJ/m^2",
                                     "MJ/m^2",
                                     "MJ/m^2",
                                     "MJ/m^2",
                                     "MJ/m^2",
                                     "MJ/m^2",
                                     "MJ/m^2",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "Celsius degree",
                                     "m/s",
                                     "m/s",
                                     "m/s",
                                     "m/s",
                                     "m/s",
                                     "m/s",
                                     "m/s",
                                     "m",
                                     "m",
                                     "m"))

knitr::kable(datasets_info, 'latex', 
             caption  = 'Detail information about covariates used in modelling.', 
             label = "cov",
             booktabs = TRUE,
             longtable = T,
             col.names = c("Covariate name", "description", "Units"))  %>%
kable_styling(latex_options = c("repeat_header"))

  
```

\normalsize

(ref:clutforest) COVER look up table [@forest]
(ref:hlutforest) HEIGHT look up table [@forest]

```{r results='asis'}
tibble(COVER = c(1,2,3,4,5,6), Forest = c("20-50%", "50-80%", ">80%", "n/a", ">=20%", "<20%"), des = c("Woodland", "Open", "Closed", "Plantation", "Unknown", "Non forest")) %>%
  knitr::kable('latex',
               col.names = c("COVER code", "Forest crown cover", "Description"),
               label = "cover",
               caption = '(ref:clutforest)',
               booktabs = T)
```


```{r}
tibble(COVER = c(1,2,3,4,5,6), Forest = c("2m-10m", "10m-30m", ">30m", "n/a", ">=2m", ""), des = c("Low", "Medium", "Tall", "Plantation", "Unknown", "Non forest")) %>%
  knitr::kable('latex',
               col.names = c("HEIGHT code", "Forest height class", "Description"),
               label = "height",
               caption = '(ref:hlutforest)',
               booktabs = T)
```



